baseURL = "https://allinleeyl.github.io/homepage/"
languageCode = 'en-us'
title = "Allin Lee's Home"
theme = "PaperMod"

enableRobotsTXT = true
enableInlineShortcodes = true

[params]
env = "production"
title = "Hi!"
description = "This is Allin Lee's homepage."
defaultTheme = "auto"
social = true
ShowToc = false
hideSummary = false

[params.taxonomies]
category = "categories"
tag = "tags"
series = "series"

[params.homeInfoParams]
Title = "Allin's Home"
Content = '''
Kia ora, 👋

My name is Allin Lee. I am a CS student now. My hobby is finding new things and giving it a try constantly. 
This is a place where I'd like to share my experience and ideas.

🎓**MEng** Computer Technology, University of Chinese Academy of Sciences, 2022-Now

🎓**BSc** Computer Science and Technology, Nankai University, 2018-2022
'''

[[params.socialIcons]]
name = "github"
title = "View Source on Github"
url = "https://github.com/AllinLeeYL"

[menus]
[[menus.main]]
name = 'Tags'
url = 'tags/'
weight = 10
[[menus.main]]
name = 'Archive'
url = 'archives/'
weight = 5
